### ISSUE TITLE
Feature request: add a command to display location of the phrases.json file

### ISSUE THREAD

**Issue by joeynguyen** [bostrt/quikey#19]
Not sure if this functionality already exists.  I apologize that I couldn't find it if it does.

It'd be nice if there was a command or some way to display to the user where `phrases.json` exists in their computer.  That would make it easy for someone to back up or sync their shortcuts from one computer to another.

I was able to dig through the code in this repo and figure out that it's saved to a file named phrases.json and I found it using: `find . -name phrases.json` from my home directory but having a command for it would be much nicer :)

**Comment by bostrt** [comment]
@joeynguyen I'll start looking at this a bit more next week. Thanks for the report!

**Comment by bostrt** [comment]
I think I'll add something like `qk status` and it will show this sort of information.

**Comment by qalisto** [comment]
Sir:

We respectfully request that installation of QK be clearly and linearly 
laid out for new Linux OS users.

It would be great if, from the standpoint of a machine with Bare Bones 
Debian, what apps and dependency apps should be installed in their 
logical sequential order.

If such document exist besides the readme on GitHub that we may have 
missed.  Excuse us.

QK looks to be a more UX friendly alternative to AUTOKEY on Linux, which 
is ... "clunky"

But we are having difficulty getting it to work.

So a S x S 1-pager would be great.

Thank you for your generous work.

-Richard

**Comment by bostrt** [comment]
@joeynguyen version 0.1.0 includes `qk status` which should resolve your request. Please take a look and update on your side:

```
$ pip3 install --user -U quikey
$ pip3 show quikey | grep Version
Version: 0.1.0

$ qk status
Quikey daemon running (PID: 32536)
Database location: /home/user/.local/share/quikey/phrases.json

```

**Comment by SanskritFritz** [comment]
@bostrt 
Indeed pip installs version 0.1.0 but there is no such release or tag. Please create one, because I want to create an archlinux package for this wonderful tool.

**Comment by bostrt** [comment]
Hello!

I just noticed that today as well. I'll be fixing it this weekend.
Apologies for the inconvenience :)

**Comment by SanskritFritz** [comment]
:smile: 
https://aur.archlinux.org/packages/quikey/

**Comment by SanskritFritz** [comment]
May I have some more questions as well:
1. What is ```qk ls --show-all``` doing compated to ```qk ls```?
2. What can tags be used for?

**Comment by bostrt** [comment]
Awesome! Thank you so much for helping out! I'll let you know once I have a
tag up.

**Comment by bostrt** [comment]
@SanskritFritz  Thanks for your patience, I'm back at a computer for a bit for the weekend. The `0.1.0` tag is available now:

  https://github.com/bostrt/quikey/tree/0.1.0

> May I have some more questions as well:
> 
>     1. What is `qk ls --show-all` doing compared to `qk ls`?
The key to the `--show-all` flag is that it prints the entire phrase column without truncating with ellipsis. I have added issue #24 for tracking this. Thanks!

>     2. What can tags be used for?

I'm considering removing this feature for the exact question you asked. What good are they? I originally added them because I thought a search or sort feature based on tags would be helpful for a large database. The fork in the road I am at right now is:

A) Is the feature just not completed (i.e. add search and sort capabilities)
B) Is the feature just not going to be useful and need to be removed?

If you have some input on this feel free to respond here or open up a new issue to continue discussion.

**Comment by SanskritFritz** [comment]
Thanks, I updated the AUR package just now.

Also thank you for your answers.
2. I too thought tags could prove useful for searching. I actually would prefer using tags for manipulating (editing, removing) entries because right when I type in the name (like qk rm --name=hello) it gets expanded but this time unwanted :smile: So, using qk rm tag=HEY would help alot with that problem. I would even say, --name is a rather unfortunate name for that. But that is another story and changing that would break compatibilty with older versions.

**Comment by bostrt** [comment]
Great :) Thanks again for packaging quieky for Arch! I'll be doing the same for RHEL/Fedora (then Debian later once I read up on how to).

I will consider your points about the tag vs name, I may mention you in another GitHub request after I have some time to think on it.
